--- #YAML:1.0
name:               Object-Result
version:            0.000002
abstract:           Allow subs to build and return objects on-the-fly
author:
    - Damian Conway <DCONWAY@CPAN.org>
license:            artistic2
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Keyword::Simple:     0
    Method::Signatures:  0
    perl:                5.014
    PPI:                 0
    Test::More:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
